---
- name: Preparing Ubuntu for AetherFlow
  hosts: local
  become: yes   # run commands with sudo privileges

  tasks:
    - name: Update cache apt
      apt:
        update_cache: yes

    - name: Instalaction of support packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Docker instalation
      apt:
        name: docker.io
        state: present

    - name: Making sure Docker is running
      service:
        name: docker
        state: started
        enabled: yes   # this makes Docker start automaticlly after restaring system

    - name: Download and install K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:   # run this command only if the file does not already exists
        creates: /usr/local/bin/k3s   # if this file already exists do not perform this task again

    - name: Wait for the configuration file to be wolcomed
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml

    - name: Change the permission on the config file
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm 
